name: Park Closed Today

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Park Closed
      run: |
        git config --global user.name '${{ secrets.REPO_USER_NAME }}'
        git config --global user.email '${{ secrets.REPO_USER_EMAIL }}'
        ./closed.sh commit
