name: Fetch Hours

on:
  schedule:
    - cron: '47 1,11,15,17,20,23 * * *'
    
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Ruby Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Fetch Hours
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        git config --global user.name '${{ secrets.REPO_USER_NAME }}'
        git config --global user.email '${{ secrets.REPO_USER_EMAIL }}'
        ruby fetchAll.rb commit update
