name: Fetch Hours

on:
  schedule:
    - cron: '47 1,11,15,17,20,23 * * *'
    
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Ruby Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Fetch Hours
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions"
        ruby fetchAll.rb commit update
