name: Fetch Hours

on:
  schedule:
    - cron: '05 13 * * *'
    
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Fetch Hours
      run: |
        git config --global user.name '${{ secrets.REPO_USER_NAME }}'
        git config --global user.email '${{ secrets.REPO_USER_EMAIL }}'
        ./fetch.sh commit
