name: Create PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Body
        run: |
          echo "BODY"
          cat <<END > body.txt
          MASTER -> STAGING

          This PR triggers CircleCI builds: 
          https://google.com

          Wait for apps to be built and processed, then:

          - Trigger Pipeline, "submit" = app version
          - Merge PR to staging after successfully submitting for review

          END
          cat body.txt
